roll iniciative command
alexwendergithub/discord_bot pull request #9
Opened 2024-08-30 04:55 UTC by asafe-fernandes

2024-09-01 21:04 UTC, Boeno236 commented
q bosta ein asafekkkkkkkkkkk

2024-09-09 00:34 UTC, alexwendergithub requested changes
use a rolagem ja criada para rolar iniciativa

2024-09-11 10:40 UTC, alexwendergithub requested changes
Nome das variaveis devem ser mais claros(evite i ou j como nome se possivel), alguns for podem sem escritos de um jeito um pouco melhor, as funcoes devem possuir comentario explicando o que elas fazem e ajeitar espaçamento no código.

2024-09-13 09:26 UTC, alexwendergithub approved these changes

2024-09-13 09:28 UTC, merged